{
  "functions": {
    "save-to-google-sheet": {
      "timeout_seconds": 60
    },
    "generate-monthly-pdf": {
      "timeout_seconds": 300
    },
    "send-monthly-email": {
      "timeout_seconds": 300
    }
  }
}